slc6-gcc48:
  tags:
    - docker
  image: clicdp/slc6-base
  script:
    - export GCC_VERSION="4.8.5"
    - export BUILD_TYPE="dbg"
    - source .gitlab-ci.d/init_x86_64.sh
    - mkdir build 
    - cd build
    - cmake -DBoost_NO_BOOST_CMAKE=ON -GNinja -DCMAKE_BUILD_TYPE=Debug ..
    - ninja
    - ninja install
    - . ../bin/thislcgeo.sh
    - ctest --output-on-failure -j4
    - cd ..
    - rm -rf .git
    - sshpass -p $CLICTEL_PASS rsync -arv -e ssh --delete . clictel@lxplus:/afs/cern.ch/eng/clic/software/lcgeo/x86_64-slc6-gcc48-opt


slc6-gcc49:
  tags:
    - docker
  image: clicdp/slc6-base
  script:
    - export GCC_VERSION="4.9.3"
    - export BUILD_TYPE="dbg"
    - source .gitlab-ci.d/init_x86_64.sh
    - mkdir build 
    - cd build
    - cmake -DBoost_NO_BOOST_CMAKE=ON -GNinja -DCMAKE_BUILD_TYPE=Debug ..
    - ninja
    - ninja install
    - . ../bin/thislcgeo.sh
    - ctest --output-on-failure -j4
    - cd ..
    - rm -rf .git
    - sshpass -p $CLICTEL_PASS rsync -arv -e ssh --delete . clictel@lxplus:/afs/cern.ch/eng/clic/software/lcgeo/x86_64-slc6-gcc49-opt


centos7-gcc49:
  tags:
    - docker
  image: clicdp/cc7-base
  script:
    - export GCC_VERSION="4.9.3"
    - export BUILD_TYPE="dbg"
    - source .gitlab-ci.d/init_x86_64.sh
    - mkdir build 
    - cd build
    - cmake -DBoost_NO_BOOST_CMAKE=ON -GNinja -DCMAKE_BUILD_TYPE=Debug ..
    - ninja
    - ninja install
    - . ../bin/thislcgeo.sh
    - ctest --output-on-failure -j4
    - cd ..
    - rm -rf .git
    - sshpass -p $CLICTEL_PASS rsync -arv -e ssh --delete . clictel@lxplus:/afs/cern.ch/eng/clic/software/lcgeo/x86_64-centos7-gcc49-opt
